ARG RCLONE_VERSION="1.70.1"

FROM ubuntu:noble AS builder
ARG RCLONE_VERSION

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    ca-certificates \
    golang-go \
    wget \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Download, build, and optimize the rclone binary
RUN wget -q "https://github.com/rclone/rclone/releases/download/v${RCLONE_VERSION}/rclone-v${RCLONE_VERSION}.tar.gz" \
    && tar -xzf "rclone-v${RCLONE_VERSION}.tar.gz" \
    && rm "rclone-v${RCLONE_VERSION}.tar.gz" \
    && cd "rclone-v${RCLONE_VERSION}" \
    && go build -v -ldflags "-s -w" \
    && mv rclone /usr/local/bin/

FROM ubuntu:noble AS app

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && \
    apt-get install --no-install-recommends -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin/ /usr/local/bin/
